name: Download and unzip sing-box

on:
  workflow_dispatch:  # 手动触发

jobs:
  unzip-job:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download sing-box.zip
        shell: powershell
        run: |
          $zipUrl  = "https://github.com/gumingxin/sing-box-subscribe/raw/refs/heads/main/sing-box.zip"
          $zipPath = "sing-box.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing

      - name: Unzip sing-box.zip
        shell: powershell
        run: |
          $destPath = "."
          Expand-Archive -Path "sing-box.zip" -DestinationPath $destPath -Force

      - name: Commit and push sing-box.exe
        shell: powershell
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add sing-box.exe
          if (git status --porcelain) {
            git commit -m "Add sing-box.exe from zip"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          } else {
            Write-Host "No changes to commit."
          }
