name: Convert_Xiaoxin_JSON_to_SRS

on:
  push:
    paths:
      - 'xiaoxin/*.json'   # 只要 xiaoxin 文件夹下的 json 文件有变动就触发
  schedule:
    - cron: '0 18 * * *'   # UTC 时间 18 点，相当于北京时间 02:00
  workflow_dispatch:       # 允许手动触发

jobs:
  convert-rules:
    runs-on: windows-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. 下载 sing-box
      - name: Download sing-box v1.9.4
        shell: powershell
        run: |
          $exePath = "./sing-box.exe"
          $url = "https://github.com/SagerNet/sing-box/releases/download/v1.9.4/sing-box-1.9.4-windows-amd64.zip"
          $zipFile = "sing-box.zip"

          Invoke-WebRequest -Uri $url -OutFile $zipFile -TimeoutSec 300
          Expand-Archive -Path $zipFile -DestinationPath . -Force
          Remove-Item -Path $zipFile

          $exeFile = Get-ChildItem -Recurse -Filter "*sing-box*.exe" | Select-Object -First 1
          Rename-Item -Path $exeFile.FullName -NewName $exePath -Force

      # 3. 扫描并编译 xiaoxin 下的所有 json → srs
      - name: Convert JSON to SRS
        shell: powershell
        run: |
          $exePath = "./sing-box.exe"
          $jsonFiles = Get-ChildItem -Path "xiaoxin" -Filter "*.json"

          foreach ($json in $jsonFiles) {
            $srsFile = [System.IO.Path]::ChangeExtension($json.FullName, ".srs")
            Write-Host "Converting $($json.Name) -> $(Split-Path $srsFile -Leaf)"
            & $exePath rule-set compile --output $srsFile $json.FullName

            if ($LASTEXITCODE -ne 0) {
              Write-Error "Conversion failed for $($json.Name)"
              exit 1
            }
          }

      # 4. 提交并推送
      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.TOKEN }}
        shell: powershell
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git add xiaoxin/*.srs

          if (git status --porcelain) {
            git commit -m "Auto-compile updated JSON → SRS"
            git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          } else {
            Write-Host "No changes to commit."
          }
