name: Convert sing-box JSON to SRS

on:
  push:
    paths:
      - 'config.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download sing-box
        run: |
          mkdir singbox && cd singbox
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-$(uname -s | tr A-Z a-z)-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          chmod +x sing-box

      - name: Convert config.json to config.srs
        run: |
          ./singbox/sing-box convert -c config.json -o config.srs

      - name: Commit and push .srs file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add config.srs
          git commit -m "Auto convert config.json to config.srs"
          git push