name: Convert sing-box JSON to SRS

on:
  push:
    paths:
      - 'xiaoxin/config.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download sing-box
        run: |
          mkdir singbox && cd singbox
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          chmod +x sing-box

      - name: Convert xiaoxin/config.json to xiaoxin/config.srs
        run: |
          ./singbox/sing-box convert -c xiaoxin/config.json -o xiaoxin/config.srs

      - name: Commit and push updated .srs file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add xiaoxin/config.srs
          git commit -m "Auto update config.srs from config.json" || echo "No changes to commit"
          git push